### ISSUE TITLE
Minor relative path issue

### ISSUE THREAD

**Issue by Doosty** [Ovski4/docker-borgbackup-cron#1]
I needed to change all occurances of "~/.ssh" in entrypoint.sh to absolute path "/root/.ssh". The known hosts would not get created and the app would fail. Otherwise all good, thanks.

**Comment by Ovski4** [comment]
I''d like to understand what the root cause is for your issue before updating this image.

Running the following command
```
docker run -it -e BORG_PASSPHRASE=test ovski/borgbackup-cron:latest bash -c "echo \$HOME"
# or
docker run -it -e BORG_PASSPHRASE=test ovski/borgbackup-cron:latest bash -c "cd ~ && pwd"
```
Outputs `/root`, so I don't see how updating occurrences of  `~/.ssh` would fix things for this image.

**Comment by Doosty** [comment]
Ok nevermind i was using v1.0.0 of your image at first with docker compose which does actually work a bit differently for example `command: cd ~` or `ls ~` doesnt work so i got confused. And when i rebuilt your image from github it started working, probably because of a newer image not anything else. Sorry, false alarm.
